# Generated by Django 5.0 on 2023-12-29 09:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=125)),
                ('brand', models.CharField(max_length=125)),
                ('category', models.CharField(max_length=125)),
                ('image_url', models.URLField(blank=True)),
                ('base_price', models.FloatField()),
                ('final_price', models.FloatField()),
                ('savings_price', models.FloatField(default=0.0)),
                ('url', models.URLField(blank=True)),
                ('short_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
