[tool.isort]
force_single_line = true # использовать однострочные импорты, когда это возможно.
line_length = 120 # Максимальная длинна строки
order_by_type = false # не будет группировать импорты по типу (стандартные библиотеки, сторонние пакеты, локальные импорты)
profile = 'black' # Указание профиля форматирования