# Generated by Django 5.0 on 2024-02-05 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=250, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('product_id', models.CharField(max_length=75, unique=True, verbose_name='product_id')),
                ('name', models.CharField(blank=True, default='No name provided', max_length=200, verbose_name='name')),
                ('brand', models.CharField(blank=True, default='No brand provided', max_length=100, verbose_name='brand')),
                ('image_url', models.URLField(blank=True, default='No image provided', verbose_name='image_url')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, message='Must be greater than or equal to 1.0.')], verbose_name='base_price')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, message='Must be greater than or equal to 1.0.')], verbose_name='final_price')),
                ('savings_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Must be greater than or equal to 0.0.')], verbose_name='savings_price')),
                ('url', models.URLField(blank=True, default='No url provided', verbose_name='url')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='short_description')),
                ('category', models.ForeignKey(default='No category provided', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
